// languages.js

const languages = [
        { code: 'abq', name: 'Abaza' },
        { code: 'af', name: 'Afrikaans' },
        { code: 'akk', name: 'Akkadian' },
        { code: 'aqz', name: 'Akuntsu' },
        { code: 'sq', name: 'Albanian' },
        { code: 'arq', name: 'Algerian Arabic' },
        { code: 'am', name: 'Amharic' },
        { code: 'grc', name: 'Ancient Greek' },
        { code: 'hbo', name: 'Ancient Hebrew' },
        { code: 'apu', name: 'Apurinã' },
        { code: 'ar', name: 'Arabic' },
        { code: 'hy', name: 'Armenian' },
        { code: 'amw', name: 'Assyrian Neo-Aramaic' },
        { code: 'bm', name: 'Bambara' },
        { code: 'eu', name: 'Basque' },
        { code: 'bej', name: 'Beja' },
        { code: 'be', name: 'Belarusian' },
        { code: 'bn', name: 'Bengali' },
        { code: 'bho', name: 'Bhojpuri' },
        { code: 'bor', name: 'Borôro' },
        { code: 'br', name: 'Breton' },
        { code: 'bg', name: 'Bulgarian' },
        { code: 'ca', name: 'Catalan' },
        { code: 'ceb', name: 'Cebuano' },
        { code: 'ess', name: 'Central Siberian Yupik' },
        { code: 'zh', name: 'Chinese' },
        { code: 'ckt', name: 'Chukot' },
        { code: 'cu', name: 'Church Slavic' },
        { code: 'cop', name: 'Coptic' },
        { code: 'hr', name: 'Croatian' },
        { code: 'cs', name: 'Czech' },
        { code: 'da', name: 'Danish' },
        { code: 'nl', name: 'Dutch' },
        { code: 'emr', name: 'Emerillon' },
        { code: 'en', name: 'English' },
        { code: 'myv', name: 'Erzya' },
        { code: 'et', name: 'Estonian' },
        { code: 'fo', name: 'Faroese' },
        { code: 'fi', name: 'Finnish' },
        { code: 'fr', name: 'French' },
        { code: 'gl', name: 'Galician' },
        { code: 'de', name: 'German' },
        { code: 'aln', name: 'Gheg Albanian' },
        { code: 'got', name: 'Gothic' },
        { code: 'gub', name: 'Guajajára' },
        { code: 'gn', name: 'Guarani' },
        { code: 'he', name: 'Hebrew' },
        { code: 'hi', name: 'Hindi' },
        { code: 'hit', name: 'Hittite' },
        { code: 'hu', name: 'Hungarian' },
        { code: 'is', name: 'Icelandic' },
        { code: 'id', name: 'Indonesian' },
        { code: 'ga', name: 'Irish' },
        { code: 'it', name: 'Italian' },
        { code: 'ja', name: 'Japanese' },
        { code: 'jv', name: 'Javanese' },
        { code: 'quc', name: 'K\'iche\'' },
        { code: 'kxp', name: 'Kangri' },
        { code: 'krl', name: 'Karelian' },
        { code: 'kgf', name: 'Karo (Brazil)' },
        { code: 'kk', name: 'Kazakh' },
        { code: 'xsi', name: 'Khunsari' },
        { code: 'ky', name: 'Kirghiz' },
        { code: 'koi', name: 'Komi-Permyak' },
        { code: 'kv', name: 'Komi-Zyrian' },
        { code: 'ko', name: 'Korean' },
        { code: 'la', name: 'Latin' },
        { code: 'lv', name: 'Latvian' },
        { code: 'olo', name: 'Livvi' },
        { code: 'nds', name: 'Low German' },
        { code: 'mij', name: 'Madi' },
        { code: 'mpu', name: 'Makuráp' },
        { code: 'ml', name: 'Malayalam' },
        { code: 'mt', name: 'Maltese' },
        { code: 'gv', name: 'Manx' },
        { code: 'mr', name: 'Marathi' },
        { code: 'gun', name: 'Mbyá Guaraní' },
        { code: 'el', name: 'Modern Greek' },
        { code: 'mdf', name: 'Moksha' },
        { code: 'myu', name: 'Mundurukú' },
        { code: 'mbh', name: 'Nayini' },
        { code: 'nap', name: 'Neapolitan' },
        { code: 'yrl', name: 'Nhengatu' },
        { code: 'pcm', name: 'Nigerian Pidgin' },
        { code: 'kmr', name: 'Northern Kurdish' },
        { code: 'se', name: 'Northern Sami' },
        { code: 'no', name: 'Norwegian' },
        { code: 'fro', name: 'Old French' },
        { code: 'sga', name: 'Old Irish' },
        { code: 'orv', name: 'Old Russian' },
        { code: 'otk', name: 'Old Turkish' },
        { code: 'fa', name: 'Persian' },
        { code: 'pl', name: 'Polish' },
        { code: 'pt', name: 'Portuguese' },
        { code: 'ro', name: 'Romanian' },
        { code: 'bua', name: 'Russia Buriat' },
        { code: 'ru', name: 'Russian' },
        { code: 'sa', name: 'Sanskrit' },
        { code: 'say', name: 'Saya' },
        { code: 'gd', name: 'Scottish Gaelic' },
        { code: 'sr', name: 'Serbian' },
        { code: 'si', name: 'Sinhala' },
        { code: 'sms', name: 'Skolt Sami' },
        { code: 'sk', name: 'Slovak' },
        { code: 'sl', name: 'Slovenian' },
        { code: 'soi', name: 'Soi' },
        { code: 'apc', name: 'South Levantine Arabic' },
        { code: 'es', name: 'Spanish' },
        { code: 'sv', name: 'Swedish' },
        { code: 'sfs', name: 'Swedish Sign Language' },
        { code: 'gsw', name: 'Swiss German' },
        { code: 'tl', name: 'Tagalog' },
        { code: 'ta', name: 'Tamil' },
        { code: 'tt', name: 'Tatar' },
        { code: 'te', name: 'Telugu' },
        { code: 'th', name: 'Thai' },
        { code: 'tup', name: 'Tupinambá' },
        { code: 'tr', name: 'Turkish' },
        { code: 'ug', name: 'Uighur' },
        { code: 'uk', name: 'Ukrainian' },
        { code: 'umb', name: 'Umbrian' },
        { code: 'hsb', name: 'Upper Sorbian' },
        { code: 'ur', name: 'Urdu' },
        { code: 'urb', name: 'Urubú-Kaapor' },
        { code: 'vi', name: 'Vietnamese' },
        { code: 'wbp', name: 'Warlpiri' },
        { code: 'cy', name: 'Welsh' },
        { code: 'hyw', name: 'Western Armenian' },
        { code: 'fy', name: 'Western Frisian' },
        { code: 'wo', name: 'Wolof' },
        { code: 'xav', name: 'Xavánte' },
        { code: 'sjo', name: 'Xibe' },
        { code: 'sah', name: 'Yakut' },
        { code: 'yo', name: 'Yoruba' },
        { code: 'yue', name: 'Yue Chinese' },
        { code: 'nhn', name: 'Nahuatl' }
    ];

export default languages; // For ES6 modules
